### ISSUE TITLE
Node v4 Compatibility 

### ISSUE THREAD

**Issue by EvanLovely** [phase2/generator-gadget#23]
Currently `yo gadget` doesn't work with node v4.2.1 – here's my output:

``` bash
 ~/Sites/p2-dev-tools/test__yo-gadget  node -v
v4.2.1
 ~/Sites/p2-dev-tools/test__yo-gadget  yo gadget

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |  Welcome to Gadget, the  |
   `---------´   |   gnarly generator for   |
    ( _´U`_ )    |    Grunt Drupal Tasks!   |
    /___A___\    '--------------------------'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Machine-name of your project? test__yo-gadget
? One-line project description? A one-line description to provide context to the name.
? Which Drupal distribution would you like to use? Drupal
? Which version of Drupal would you like to use? Drupal 8

Ok, I'm going to start assembling this project...

Installing latest version of Grunt Drupal Tasks...
npm WARN peerDependencies The peer dependency grunt@>= 0.4.5 < 0.5 included from grunt-drupal-tasks will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN engine grunt-phpcs@0.4.0: wanted: {"node":"0.10.x"} (current: {"node":"4.2.1","npm":"2.14.7"})
npm WARN peerDependencies The peer dependency grunt@~0.4 included from grunt-log-headers will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.1 included from grunt-contrib-symlink will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-contrib-clean will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@>=0.4.0 included from grunt-contrib-copy will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-composer will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@>=0.4.0 included from grunt-contrib-compass will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-contrib-compress will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-mkdir will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-contrib-watch will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@>=0.4.0 included from grunt-drush will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.5 included from grunt-available-tasks will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-parallel-behat will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.1 included from grunt-newer will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.1 included from grunt-notify will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
grunt@0.4.5 node_modules/grunt
├── eventemitter2@0.4.14
├── dateformat@1.0.2-1.2.3
├── which@1.0.9
├── async@0.1.22
├── colors@0.6.2
├── getobject@0.1.0
├── lodash@0.9.2
├── rimraf@2.2.8
├── hooker@0.2.3
├── grunt-legacy-util@0.2.0
├── exit@0.1.2
├── nopt@1.0.10 (abbrev@1.0.7)
├── coffee-script@1.3.3
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.7.0)
├── iconv-lite@0.2.11
├── underscore.string@2.2.1
├── glob@3.1.21 (inherits@1.0.2, graceful-fs@1.2.3)
├── grunt-legacy-log@0.1.2 (grunt-legacy-log-utils@0.1.1, lodash@2.4.2, underscore.string@2.3.3)
├── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
└── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)

grunt-drupal-tasks@0.8.0 node_modules/grunt-drupal-tasks
├── grunt-phpmd@0.1.1
├── grunt-force-task@1.0.0
├── grunt-phpcs@0.4.0
├── grunt-contrib-clean@0.6.0 (rimraf@2.2.8)
├── grunt-concurrent@1.0.0 (async@0.9.2, pad-stdio@1.0.0)
├── grunt-drush@0.0.6 (win-spawn@2.0.0, async@0.9.2, lodash@2.4.2)
├── grunt-newer@1.1.1 (async@0.9.0, rimraf@2.2.8)
├── grunt-composer@0.4.4 (shelljs@0.2.6)
├── grunt-shell@1.1.2 (chalk@1.1.1)
├── grunt-contrib-copy@0.8.0 (file-sync-cmp@0.1.1, chalk@0.5.1)
├── grunt-notify@0.4.1 (stack-parser@0.0.1, which@1.0.9, semver@4.3.6)
├── grunt-parallel-behat@0.3.6 (underscore@1.4.4, glob@3.2.11)
├── grunt-contrib-watch@0.6.1 (async@0.2.10, lodash@2.4.2, gaze@0.5.2, tiny-lr-fork@0.0.5)
├── grunt@0.4.5 (eventemitter2@0.4.14, dateformat@1.0.2-1.2.3, which@1.0.9, async@0.1.22, colors@0.6.2, getobject@0.1.0, lodash@0.9.2, rimraf@2.2.8, hooker@0.2.3, grunt-legacy-util@0.2.0, exit@0.1.2, coffee-script@1.3.3, iconv-lite@0.2.11, nopt@1.0.10, underscore.string@2.2.1, glob@3.1.21, minimatch@0.2.14, grunt-legacy-log@0.1.2, findup-sync@0.1.3, js-yaml@2.0.5)
├── grunt-contrib-symlink@0.3.0
├── grunt-mkdir@0.1.2
├── grunt-log-headers@1.0.1
├── grunt-phplint@0.0.5 (cache-swap@0.0.6, grunt@0.4.5)
├── time-grunt@1.2.1 (date-time@1.0.0, number-is-nan@1.0.0, figures@1.4.0, hooker@0.2.3, text-table@0.2.0, chalk@1.1.1, pretty-ms@1.4.0)
├── grunt-contrib-compass@1.0.3 (dargs@2.1.0, onetime@1.0.0, async@0.9.2, tmp@0.0.24, bin-version-check@2.1.0)
├── lodash@3.9.3
├── grunt-available-tasks@0.5.7 (chalk@1.1.1, underscore.string@3.2.2, lodash@3.3.1)
├── grunt-contrib-compress@0.13.0 (prettysize@0.0.3, chalk@0.5.1, archiver@0.13.1)
└── grunt-eslint@13.0.0 (chalk@1.1.1, eslint@0.21.2)

Installed version 0.8.0 of Grunt Drupal Tasks.

Setting up Drush makefile to install Drupal Distribution drupal version 8.0.0-rc2.

   create package.json
   create .editorconfig
   create .eslintignore
   create .eslintrc
   create composer.json
   create gitignore
   create Gruntconfig.json
   create Gruntfile.js
   create phpmd.xml
   create src/libraries/.gitkeep
   create src/modules/.gitkeep
   create src/profiles/.gitkeep
   create src/project.make
   create src/sites/default/.gitkeep
   create src/static/.gitkeep
   create src/themes/.gitkeep
   create test/behat.yml
   create test/features/bootstrap/FeatureContext.php
   create test/features/example.feature
   create .gitignore
   create README.md
npm WARN engine zombie@2.5.1: wanted: {"node":"0.10.x"} (current: {"node":"4.2.1","npm":"2.14.7"})
npm WARN engine lazybird@1.0.0: wanted: {"node":"0.10.x"} (current: {"node":"4.2.1","npm":"2.14.7"})

> ws@0.6.5 install /Users/Evan/Sites/p2-dev-tools/test__yo-gadget/node_modules/zombie/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> contextify@0.1.14 install /Users/Evan/Sites/p2-dev-tools/test__yo-gadget/node_modules/zombie/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

2015-10-29 14:08:35.055 xcodebuild[28271:6086223] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMQuickHelp.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/contextify/src/contextify.o
In file included from ../src/contextify.cc:3:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/Evan/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/Evan/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/Evan/.node-gyp/4.2.1/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/Evan/.node-gyp/4.2.1/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/contextify.cc:3:
../node_modules/nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/contextify.cc:3:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/contextify.cc:1:
In file included from /Users/Evan/.node-gyp/4.2.1/include/node/node.h:42:
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/contextify.cc:1:
In file included from /Users/Evan/.node-gyp/4.2.1/include/node/node.h:42:
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/contextify.cc:1:
In file included from /Users/Evan/.node-gyp/4.2.1/include/node/node.h:42:
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/contextify.cc:1:
In file included from /Users/Evan/.node-gyp/4.2.1/include/node/node.h:42:
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/contextify.cc:1:
In file included from /Users/Evan/.node-gyp/4.2.1/include/node/node.h:42:
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Value *volatile' from incompatible type 'v8::Context *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:267:10: note: in instantiation of function template specialization 'v8::Local<v8::Value>::Local<v8::Context>' requested here
  return NanNew(val);
         ^
../src/contextify.cc:159:16: note: in instantiation of function template specialization '_NanEnsureLocal<v8::Local<v8::Context> >' requested here
        return NanEscapeScope(NanNew<Context>(
               ^
../node_modules/nan/nan.h:398:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^
In file included from ../src/contextify.cc:1:
In file included from /Users/Evan/.node-gyp/4.2.1/include/node/node.h:42:
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Context *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:159:16: note: in instantiation of function template specialization 'v8::Local<v8::Context>::Local<v8::Value>' requested here
        return NanEscapeScope(NanNew<Context>(
               ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/contextify.cc:1:
In file included from /Users/Evan/.node-gyp/4.2.1/include/node/node.h:42:
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:7380:3: error: assigning to 'v8::Integer *volatile' from incompatible type 'v8::Value *'
  TYPE_CHECK(T, S);
  ^~~~~~~~~~~~~~~~
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:211:13: note: in instantiation of function template specialization 'v8::ReturnValue<v8::Integer>::Set<v8::Value>' requested here
            NanReturnValue(NanNew<Integer>(None));
            ^
../node_modules/nan/nan.h:401:61: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsureLocal(value))
                                                            ^
In file included from ../src/contextify.cc:1:
In file included from /Users/Evan/.node-gyp/4.2.1/include/node/node.h:42:
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:7380:3: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
  TYPE_CHECK(T, S);
  ^~~~~~~~~~~~~~~~
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:225:13: note: in instantiation of function template specialization 'v8::ReturnValue<v8::Boolean>::Set<v8::Value>' requested here
            NanReturnValue(NanNew<Boolean>(false));
            ^
../node_modules/nan/nan.h:401:61: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsureLocal(value))
                                                            ^
In file included from ../src/contextify.cc:1:
In file included from /Users/Evan/.node-gyp/4.2.1/include/node/node.h:42:
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:7380:3: error: assigning to 'v8::Array *volatile' from incompatible type 'v8::Value *'
  TYPE_CHECK(T, S);
  ^~~~~~~~~~~~~~~~
/Users/Evan/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:236:13: note: in instantiation of function template specialization 'v8::ReturnValue<v8::Array>::Set<v8::Value>' requested here
            NanReturnValue(blank);
            ^
../node_modules/nan/nan.h:401:61: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsureLocal(value))
                                                            ^
14 errors generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Evan/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/Evan/.nvm/versions/node/v4.2.1/bin/node" "/Users/Evan/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Evan/Sites/p2-dev-tools/test__yo-gadget/node_modules/zombie/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/Evan/.nvm/versions/node/v4.2.1/bin/node" "/Users/Evan/.nvm/versions/node/v4.2.1/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Evan/Sites/p2-dev-tools/test__yo-gadget/npm-debug.log

Gadget has finished setting up the Drupal project scaffold with Grunt Drupal Tasks!

Run `grunt` to run the first build of this project.
```

**Comment by arithmetric** [comment]
This error comes from the contextify module which is a dependency of the zombie module (which is optional). The current GDT example uses the older 2.x version of zombie. By updating to use zombie 4.x, this issue seems to be resolved, however zombie 4.x requires io.js or Node 4+.

After updating many of the package dependencies (see branch feature/update_deps), GDT was able to install and run successfully.

This revealed one other issue with the Zombie testing stack: The mink-zombie-driver has an incompatibility with the flat node_modules structure with Node 4/npm 3. See: https://github.com/minkphp/MinkZombieDriver/blob/master/src/NodeJS/Server/ZombieServer.php#L64

**Comment by EvanLovely** [comment]
@illepic ^^^
Thanks Joe! Let's try to get all our stuff on 4.2.x LTS soon!

**Comment by grayside** [comment]
According to [Travis](https://travis-ci.org/phase2/generator-gadget) we're good on this. Are we ready to close?

**Comment by EvanLovely** [comment]
Happily!
